--------------------------------------------------------
--  DDL for Table BNSATE00_EMPRESA
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE00_EMPRESA" 
   (	"B00_ID_EMP" NUMBER(10,0), 
	"B02_REP" NUMBER(10,0), 
	"B00_NUM_CUENTA_CORRIENTE" VARCHAR2(20), 
	"B00_NUM_RUC" VARCHAR2(11), 
	"B00_TIPO" VARCHAR2(20), 
	"B00_RAZON_SOCIAL" VARCHAR2(200), 
	"B00_DIRECCION" VARCHAR2(200), 
	"B00_UBIGEO" VARCHAR2(6), 
	"B00_REFERENCIA" VARCHAR2(100), 
	"B00_NOMBRE_CORTO" VARCHAR2(30), 
	"B00_CIC" VARCHAR2(12), 
	"B00_TELEFONO" VARCHAR2(12), 
	"B00_DIRECCION_MC" VARCHAR2(107)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE01_EST_EMPRESA
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE01_EST_EMPRESA" 
   (	"B01_ID_EST" NUMBER(10,0), 
	"B00_ID_EMP" NUMBER(10,0), 
	"B01_FEC_AFILIACION" DATE, 
	"B01_FEC_DESAFILIACION" DATE, 
	"B01_MOTIVO" VARCHAR2(200), 
	"B01_DETALLE" VARCHAR2(500), 
	"B01_USUARIO_AFI" VARCHAR2(10), 
	"B01_USUARIO_DESA" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE02_USUARIO
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE02_USUARIO" 
   (	"B02_REP" NUMBER(10,0), 
	"B02_TIPO_DOCUMENTO" VARCHAR2(1), 
	"B02_NUM_DOCUMENTO" VARCHAR2(15), 
	"B02_NOMBRES" VARCHAR2(50), 
	"B02_CORREO" VARCHAR2(50), 
	"B02_TELEFONO_FIJO" VARCHAR2(12), 
	"B02_TELEFONO_MOVIL" VARCHAR2(12), 
	"B02_ESTADO" VARCHAR2(10), 
	"B02_FEC_REGISTRO" DATE, 
	"B02_COD_TELEFONO" VARCHAR2(12), 
	"B02_ANEXO" VARCHAR2(10), 
	"B02_OPERADORA" VARCHAR2(1), 
	"B02_CORREO_PERSONAL" VARCHAR2(100), 
	"B02_USERNAME" VARCHAR2(20), 
	"B02_PERFIL_USUARIO" NUMBER(10,0), 
	"B02_APPATERNO" VARCHAR2(30), 
	"B02_APMATERNO" VARCHAR2(30), 
	"B02_REP_CREADOR" NUMBER(10,0), 
	"B02_FLAG_CAMBIO_CLAVE" VARCHAR2(1), 
	"B02_INTENTOS_INIC_SESION" NUMBER(1,0), 
	"B02_FECHA_ACT_CLAVE" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE03_REP_EMP
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE03_REP_EMP" 
   (	"B03_REPE" NUMBER(10,0), 
	"B00_ID_EMP" NUMBER(10,0), 
	"B02_REP" NUMBER(10,0), 
	"B03_FEC_REGISTRO" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE04_ASIGNACION
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE04_ASIGNACION" 
   (	"B04_ID_CAS" NUMBER(6,0), 
	"B05_ID_TAR" NUMBER(6,0), 
	"B04_CODIGO_ASIGNACION" VARCHAR2(15), 
	"B04_FECHA_INICIO_LINEA" DATE, 
	"B04_FECHA_FIN_LINEA" DATE, 
	"B04_FECHA_REGISTRO" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE05_TARJETA
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE05_TARJETA" 
   (	"B05_ID_TAR" NUMBER(10,0), 
	"B00_ID_EMP" NUMBER(10,0), 
	"B06_ID_CLI" NUMBER(10,0), 
	"B02_REP" NUMBER(10,0), 
	"B05_NUM_TARJETA" VARCHAR2(19), 
	"B05_USO_DISP_EFECT" VARCHAR2(10), 
	"B05_USO_EXTRANJERO" VARCHAR2(2), 
	"B05_TIPO_TARJETA" VARCHAR2(6), 
	"B05_OBSERVACIONES" VARCHAR2(100), 
	"B05_TIPO_MONEDA" VARCHAR2(5), 
	"B05_ENTREGA_UBICACION" VARCHAR2(1), 
	"B05_ENTREGA_AGENCIA_BN" VARCHAR2(100), 
	"B05_ENTREGA_DIRECCION" VARCHAR2(100), 
	"B05_ENTREGA_REFERENCIA" VARCHAR2(200), 
	"B05_NRO_AUTORIZACION" VARCHAR2(50), 
	"B05_FEC_AUTORIZACION" DATE, 
	"B05_FEC_CREACION" DATE, 
	"B05_USUARIO_CREACION" NUMBER(6,0), 
	"B05_FEC_INICIO_LINEA" DATE, 
	"B05_FEC_TERMINO_LINEA" DATE, 
	"B05_MONTO_LINEA_ASIGNADO" NUMBER(10,2), 
	"B05_MONTO_LINEA_ACTUAL" NUMBER(10,2), 
	"B05_MONTO_COMPRA_USADO" NUMBER(10,2), 
	"B05_MONTO_POR_PROCESAR" NUMBER(10,2), 
	"B05_DISP_USADO" NUMBER(10,2), 
	"B05_ENTREGA_UBIGEO" VARCHAR2(50), 
	"B05_FEC_VENCIMIENTO" DATE, 
	"B05_NUM_CUENTA" VARCHAR2(19), 
	"B05_EST_CUENTA" VARCHAR2(1), 
	"B05_FEC_APERTURA_CUENTA" DATE, 
	"B05_FLAG_ACT_EST_CUENTA" VARCHAR2(1), 
	"B05_EMAIL" VARCHAR2(30), 
	"B05_NUM_CELULAR" VARCHAR2(20), 
	"B05_FLAG_ACT_CONTACTO" VARCHAR2(1), 
	"B05_OPERADOR_CELULAR" VARCHAR2(1), 
	"B05_DISENO" NUMBER(1,0), 
	"B05_ENTREGA_DIRECCION_MC" VARCHAR2(107)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE06_CLIENTE
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE06_CLIENTE" 
   (	"B06_ID_CLI" NUMBER(10,0), 
	"B06_NOMBRES" VARCHAR2(100), 
	"B06_APPATERNO" VARCHAR2(50), 
	"B06_APMATERNO" VARCHAR2(50), 
	"B06_TIPO_DOCUMENTO" VARCHAR2(1), 
	"B06_NUM_DOCUMENTO" VARCHAR2(12), 
	"B06_FEC_NACIMIENTO" DATE, 
	"B06_EST_CIVIL" VARCHAR2(20), 
	"B06_SEXO" VARCHAR2(1), 
	"B06_TELEF_CASA" VARCHAR2(7), 
	"B06_DIRECCION" VARCHAR2(200), 
	"B06_UBIGEO" VARCHAR2(6), 
	"B06_REFERENCIA" VARCHAR2(100), 
	"B06_DIRECCION_MC" VARCHAR2(107)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE07_EST_TARJETA
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE07_EST_TARJETA" 
   (	"B07_ETA" NUMBER(10,0), 
	"B05_ID_TAR" NUMBER(10,0), 
	"B07_ESTADO" VARCHAR2(1), 
	"B07_MOTIVO" VARCHAR2(1), 
	"B07_FEC_REGISTRO" DATE, 
	"B07_USUARIO_CREA" VARCHAR2(20)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE08_USU_REP
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE08_USU_REP" 
   (	"B08_ID_USU_REP" NUMBER(6,0), 
	"B02_ID_REP" NUMBER(6,0), 
	"B02_ID_USU" VARCHAR2(20), 
	"B08_FECHA_ACTIVACION" DATE, 
	"B08_FECHA_DESACTIVACION" DATE, 
	"B08_USU_PERFIL" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE09_NOMBRE_CORTO
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE09_NOMBRE_CORTO" 
   (	"B09_NUM_RUC" VARCHAR2(11), 
	"B09_NOMBRE" VARCHAR2(19)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE10_PER_PERMISOS
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" 
   (	"B10_ID_PER" NUMBER(10,0), 
	"B11_ID_ROL" NUMBER(10,0), 
	"B10_COD_FUNCIONALIDAD" VARCHAR2(3), 
	"B10_DESCRIPCION" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE11_ROLES
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE11_ROLES" 
   (	"B11_ID_ROL" NUMBER(10,0), 
	"B11_DESCRIPCION" VARCHAR2(50), 
	"B11_ESTADO" VARCHAR2(1)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE12_RPTA_MC_TEMP
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE12_RPTA_MC_TEMP" 
   (	"B12_TRACE" NUMBER(10,0), 
	"B12_TIPO_DOCUMENTO" VARCHAR2(1), 
	"B12_NUMERO_DOCUMENTO" VARCHAR2(12), 
	"B12_APELLIDOS" VARCHAR2(30), 
	"B12_NOMBRE" VARCHAR2(30), 
	"B12_NUMERO_CUENTA" VARCHAR2(19), 
	"B12_FECHA_APERTURA_CUENTA" DATE, 
	"B12_BLOQUEO_1_CUENTA" VARCHAR2(1), 
	"B12_BLOQUEO_2_CUENTA" VARCHAR2(1), 
	"B12_NUMERO_TARJETA" VARCHAR2(19), 
	"B12_FECHA_APERTURA_TARJETA" DATE, 
	"B12_BLOQUEO_1_TARJETA" VARCHAR2(1), 
	"B12_FECHA_VENCIMIENTO_TARJETA" DATE, 
	"B12_CODIGO_PRODUCTO" VARCHAR2(3), 
	"B12_LINEA_CREDITO" NUMBER(9,0), 
	"B12_TIPO_RESPUESTA" NUMBER(1,0), 
	"B12_CODIGO_BLOQUEO" VARCHAR2(4), 
	"B12_MOTIVO_BLOQUEO" NUMBER(3,0), 
	"B12_CELULAR" NUMBER(10,0), 
	"B12_EMAIL" VARCHAR2(30), 
	"B12_FECHA_REGISTRO" DATE, 
	"B12_CODIGO_ASIGNACION" VARCHAR2(15), 
	"B12_FECHA_INICIO_LINEA" DATE, 
	"B12_FECHA_FIN_LINEA" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE13_RPTA_MEF_TEMP
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE13_RPTA_MEF_TEMP" 
   (	"B13_SEC_OPERACION" VARCHAR2(15), 
	"B13_TIPO_OPERACION" VARCHAR2(3), 
	"B13_CUENTA_CARGO" VARCHAR2(20), 
	"B13_TIPO_DOCUMENTO" VARCHAR2(2), 
	"B13_NUM_DOCUMENTO" VARCHAR2(20), 
	"B13_NOMBRE_BENEFICIARIO" VARCHAR2(100), 
	"B13_NUM_TARJETA_AUT" VARCHAR2(16), 
	"B13_FEC_INICIO_AUT" DATE, 
	"B13_FEC_FIN_AUT" DATE, 
	"B13_IMPORTE" NUMBER(13,2), 
	"B13_SEC_OPERACION_REF" VARCHAR2(15), 
	"B13_FECHA_REGISTRO" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE14_TRANSACCION_HIS
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE14_TRANSACCION_HIS" 
   (	"B14_NUM_TARJETA" VARCHAR2(19), 
	"B14_FEC_OPERACION" DATE, 
	"B14_FEC_POSTEO" DATE, 
	"B14_OPERACION" VARCHAR2(30), 
	"B14_COMERCIO" VARCHAR2(30), 
	"B14_MONTO" NUMBER(13,2), 
	"B14_AUTORIZACION_PMC" VARCHAR2(30), 
	"B14_NUM_AUTORIZACION" VARCHAR2(30), 
	"B14_ESTADO" VARCHAR2(1), 
	"B14_CUENTA_CARGO" VARCHAR2(14)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE15_CARGO_HIS
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE15_CARGO_HIS" 
   (	"B15_FEC_CORTE" DATE, 
	"B15_FEC_PROCESO" DATE, 
	"B15_CUENTA_CARGO" VARCHAR2(19), 
	"B15_MONTO_CARGADO" NUMBER(13,2), 
	"B15_MONTO_PENDIENTE" NUMBER(13,2), 
	"B15_SALDO_INICIAL" NUMBER(13,2), 
	"B15_SALDO_FINAL" NUMBER(13,2)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE16_PARAMETRO
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE16_PARAMETRO" 
   (	"B16_ID_TABLA" VARCHAR2(20), 
	"B16_ID_REGISTRO" VARCHAR2(20), 
	"B16_VALOR" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table BNSATE17_ACT_USUARIO
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE17_ACT_USUARIO" 
   (	"B02_ID_USU" VARCHAR2(4), 
	"B17_ACCION" VARCHAR2(10), 
	"B17_FUNCIONALIDAD" VARCHAR2(50), 
	"B17_FECHA" DATE, 
	"B17_REGISTRO_CAMBIOS" VARCHAR2(500)
   ) ;


--------------------------------------------------------
--  DDL for Table BNSATE18_TRACE_TRAMA
--------------------------------------------------------

  CREATE TABLE "BN_SATE"."BNSATE18_TRACE_TRAMA" 
   (	"B18_TRACE_CODE" VARCHAR2(6 BYTE), 
	"B18_FECHA" DATE, 
	"B18_DATOS" VARCHAR2(1000 BYTE)
   ) ;
   
 ALTER TABLE "BN_SATE"."BNSATE18_TRACE_TRAMA" ADD CONSTRAINT "PK_BNSATE18_TRACE_TRAMA" PRIMARY KEY ("B18_TRACE_CODE")
  USING INDEX  ENABLE;
   
   




--------------------------------------------------------
--  Constraints for Table BNSATE11_ROLES
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE11_ROLES" MODIFY ("B11_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE11_ROLES" MODIFY ("B11_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE11_ROLES" ADD CONSTRAINT "PK_BNSATE11_ROLES" PRIMARY KEY ("B11_ID_ROL")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE11_ROLES" MODIFY ("B11_ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE00_EMPRESA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" ADD CONSTRAINT "PK_BNSATE00_EMPRESA" PRIMARY KEY ("B00_ID_EMP")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_CIC" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_NOMBRE_CORTO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_UBIGEO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_TIPO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" MODIFY ("B00_NUM_RUC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE07_EST_TARJETA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE07_EST_TARJETA" MODIFY ("B07_FEC_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE07_EST_TARJETA" MODIFY ("B07_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE07_EST_TARJETA" MODIFY ("B05_ID_TAR" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE07_EST_TARJETA" ADD CONSTRAINT "PK_BNSATE07_EST_TARJETA" PRIMARY KEY ("B07_ETA")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE07_EST_TARJETA" MODIFY ("B07_ETA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE01_EST_EMPRESA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE01_EST_EMPRESA" ADD CONSTRAINT "PK_BNSATE01_EST_EMPRESA" PRIMARY KEY ("B01_ID_EST")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE01_EST_EMPRESA" MODIFY ("B01_ID_EST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE17_ACT_USUARIO
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE17_ACT_USUARIO" MODIFY ("B17_REGISTRO_CAMBIOS" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE17_ACT_USUARIO" MODIFY ("B17_FECHA" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE17_ACT_USUARIO" MODIFY ("B17_FUNCIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE17_ACT_USUARIO" MODIFY ("B17_ACCION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE17_ACT_USUARIO" MODIFY ("B02_ID_USU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE09_NOMBRE_CORTO
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE09_NOMBRE_CORTO" MODIFY ("B09_NUM_RUC" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE09_NOMBRE_CORTO" MODIFY ("B09_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE02_USUARIO
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE02_USUARIO" ADD CONSTRAINT "PK_BNSATE02_USUARIO" PRIMARY KEY ("B02_REP")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE02_USUARIO" MODIFY ("B02_REP" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE02_USUARIO" ADD CONSTRAINT "BNSATE02_USUARIO_UK1" UNIQUE ("B02_TIPO_DOCUMENTO", "B02_NUM_DOCUMENTO")
  USING INDEX  ENABLE;

--------------------------------------------------------
--  Constraints for Table BNSATE06_CLIENTE
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" ADD CONSTRAINT "PK_BNSATE06_CLIENTE" PRIMARY KEY ("B06_ID_CLI")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_ID_CLI" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_TELEF_CASA" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_SEXO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_EST_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_FEC_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_NUM_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_APPATERNO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" MODIFY ("B06_NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE06_CLIENTE" ADD CONSTRAINT "BNSATE06_CLIENTE_UK1" UNIQUE ("B06_TIPO_DOCUMENTO", "B06_NUM_DOCUMENTO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table BNSATE16_PARAMETRO
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE16_PARAMETRO" ADD CONSTRAINT "BNSATE16_PARAMETRO_PK" PRIMARY KEY ("B16_ID_TABLA", "B16_ID_REGISTRO")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE16_PARAMETRO" MODIFY ("B16_VALOR" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE16_PARAMETRO" MODIFY ("B16_ID_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE16_PARAMETRO" MODIFY ("B16_ID_TABLA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE12_RPTA_MC_TEMP
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE12_RPTA_MC_TEMP" MODIFY ("B12_FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE12_RPTA_MC_TEMP" MODIFY ("B12_TIPO_RESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE04_ASIGNACION
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" ADD CONSTRAINT "BNSATE04_CODIGO_ASIGNACIO_PK" PRIMARY KEY ("B04_ID_CAS")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" MODIFY ("B04_FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" MODIFY ("B04_FECHA_FIN_LINEA" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" MODIFY ("B04_FECHA_INICIO_LINEA" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" MODIFY ("B04_CODIGO_ASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" MODIFY ("B05_ID_TAR" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE04_ASIGNACION" MODIFY ("B04_ID_CAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE08_USU_REP
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE08_USU_REP" MODIFY ("B08_USU_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE08_USU_REP" MODIFY ("B08_FECHA_ACTIVACION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE08_USU_REP" ADD CONSTRAINT "BNSATE08_USU_REP_PK" PRIMARY KEY ("B08_ID_USU_REP")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE08_USU_REP" MODIFY ("B02_ID_USU" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE08_USU_REP" MODIFY ("B02_ID_REP" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE08_USU_REP" MODIFY ("B08_ID_USU_REP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE10_PER_PERMISOS
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" MODIFY ("B10_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" MODIFY ("B10_COD_FUNCIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" MODIFY ("B11_ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" ADD CONSTRAINT "PK_BNSATE10_PER_PERMISOS" PRIMARY KEY ("B10_ID_PER")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" MODIFY ("B10_ID_PER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BNSATE03_REP_EMP
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" ADD CONSTRAINT "PK_BNSATE03_REP_EMP" PRIMARY KEY ("B03_REPE")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" MODIFY ("B03_REPE" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" MODIFY ("B03_FEC_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" MODIFY ("B02_REP" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" MODIFY ("B00_ID_EMP" NOT NULL ENABLE);


--------------------------------------------------------
--  Constraints for Table BNSATE05_TARJETA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" ADD CONSTRAINT "BNSATE05_TARJETA_UK1" UNIQUE ("B05_NUM_TARJETA")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_ENTREGA_UBICACION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_FEC_CREACION" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_ENTREGA_UBIGEO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_NUM_CELULAR" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" ADD CONSTRAINT "PK_BNSATE05_TARJETA" PRIMARY KEY ("B05_ID_TAR")
  USING INDEX  ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_ID_TAR" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_DISENO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_OPERADOR_CELULAR" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_TIPO_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_TIPO_TARJETA" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_USO_EXTRANJERO" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B05_USO_DISP_EFECT" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B02_REP" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B06_ID_CLI" NOT NULL ENABLE);
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" MODIFY ("B00_ID_EMP" NOT NULL ENABLE);

--------------------------------------------------------
--  Ref Constraints for Table BNSATE00_EMPRESA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE00_EMPRESA" ADD CONSTRAINT "FK_BNSATE00_REFERENCE_BNSATE02" FOREIGN KEY ("B02_REP")
	  REFERENCES "BN_SATE"."BNSATE02_USUARIO" ("B02_REP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BNSATE01_EST_EMPRESA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE01_EST_EMPRESA" ADD CONSTRAINT "FK_BNSATE01_REFERENCE_BNSATE00" FOREIGN KEY ("B00_ID_EMP")
	  REFERENCES "BN_SATE"."BNSATE00_EMPRESA" ("B00_ID_EMP") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table BNSATE03_REP_EMP
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" ADD CONSTRAINT "FK_BNSATE03_REFERENCE_BNSATE00" FOREIGN KEY ("B00_ID_EMP")
	  REFERENCES "BN_SATE"."BNSATE00_EMPRESA" ("B00_ID_EMP") ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE03_REP_EMP" ADD CONSTRAINT "FK_BNSATE03_REFERENCE_BNSATE02" FOREIGN KEY ("B02_REP")
	  REFERENCES "BN_SATE"."BNSATE02_USUARIO" ("B02_REP") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table BNSATE05_TARJETA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" ADD CONSTRAINT "FK_BNSATE05_REFERENCE_BNSATE00" FOREIGN KEY ("B00_ID_EMP")
	  REFERENCES "BN_SATE"."BNSATE00_EMPRESA" ("B00_ID_EMP") ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" ADD CONSTRAINT "FK_BNSATE05_REFERENCE_BNSATE02" FOREIGN KEY ("B02_REP")
	  REFERENCES "BN_SATE"."BNSATE02_USUARIO" ("B02_REP") ENABLE;
  ALTER TABLE "BN_SATE"."BNSATE05_TARJETA" ADD CONSTRAINT "FK_BNSATE05_REFERENCE_BNSATE06" FOREIGN KEY ("B06_ID_CLI")
	  REFERENCES "BN_SATE"."BNSATE06_CLIENTE" ("B06_ID_CLI") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table BNSATE07_EST_TARJETA
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE07_EST_TARJETA" ADD CONSTRAINT "FK_BNSATE07_REFERENCE_BNSATE05" FOREIGN KEY ("B05_ID_TAR")
	  REFERENCES "BN_SATE"."BNSATE05_TARJETA" ("B05_ID_TAR") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table BNSATE10_PER_PERMISOS
--------------------------------------------------------

  ALTER TABLE "BN_SATE"."BNSATE10_PER_PERMISOS" ADD CONSTRAINT "FK_BNSATE10_REFERENCE_BNSATE11" FOREIGN KEY ("B11_ID_ROL")
	  REFERENCES "BN_SATE"."BNSATE11_ROLES" ("B11_ID_ROL") ENABLE;
